CREATE TABLE IF NOT EXISTS  books (¬
    book_id INTEGER UNSIGNED PRYMARY AUTO_INCREMENT,¬ 
    author ,¬
    title VARCHAR(100) NOT NULL,¬
    year INTEGER UNSIGNED NOT NULL DEFAULT 1900,¬
    language VARCHAR(2) NOT NULL DEFAULT 'es'COMMENT 'ISO 639-1 LANGUAGE',¬
    cover_url VARCHAR (500),¬
    price DOUBLE(6,2) NOT NULL DEFAULT 10.0,¬
    sellable TINYINT(1) DEFAULT 1,¬
    description TEXT¬
    );
